version: '3'
services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - ENV=production  # Set environment to production
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
