version: '3'
services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/code  # Ensure the volume matches the WORKDIR in the Dockerfile
    environment:
      - ENV=development  # Set environment to development
      - WATCHFILES_FORCE_POLLING=true  # Use polling for live-reload on Docker desktop environments
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
